"""empty message

Revision ID: 42353be37a4d
Revises: fb37710a7edf
Create Date: 2020-09-26 07:29:46.172426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42353be37a4d'
down_revision = 'fb37710a7edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
